### ISSUE TITLE
CPU is 100% loaded because of big gravity.

### ISSUE THREAD

**Issue by Basea** [Zonciu/Box2DSharp#1]
When I set gravity(Y) in world.Gravity/gravityScale for a body to a big value(40-50 gravityScale for example) I get my CPU 100% loaded. In the same time, I can create a lot of bodies with gravityScale<40 I get my processor works fine, as without these bodies at all.

**Comment by Zonciu** [comment]
Could you please upload a sample?

**Comment by Basea** [comment]
`            world = new World
            {
                Gravity = new System.Numerics.Vector2(0, -100), AllowSleep = true
            };`
`            BodyDef bodyDef = new BodyDef
            {
                GravityScale = 10f,
            };`
`world.Step(1f/50f, 10, 10);`
Sorry for the delay.

**Comment by Zonciu** [comment]
Your sampl works well, my guess is that you did not call World.Step method at a fixed frequency, see [FrameManager](https://github.com/Zonciu/Box2DSharp/blob/master/test/UnityTest/Assets/FrameManager.cs)
