### ISSUE TITLE
Unity test.

### ISSUE THREAD

**Issue by juliolitwin** [Zonciu/Box2DSharp#10]
Hi,

Is the Unity project really working/done? Apparently is using dependencies of ImGUI and several others, I can't compile.
Regards.

**Comment by Zonciu** [comment]
Please pull the latest commit, it should work now.

**Comment by juliolitwin** [comment]
Thanks, it worked correctly now!

Box2D is not very viable for Unity 3D, right? I saw that the performance is extremely low. I'm trying to find a 2d physics (deterministic or non-deterministic) for prediction rollback.

**Comment by Zonciu** [comment]
Unity's 2D physics engine is a wrapped C++ version of Box2D, so it would have better performance. 
According to stress tests, Box2DSharp is four times slower than Box2D.
