### ISSUE TITLE
World.Locked，并发问题。

### ISSUE THREAD

**Issue by ohsorry** [Zonciu/Box2DSharp#11]
最近又拾起box2d，重新看了一些[资料](https://www.iforce2d.net/b2dtut/removing-bodies)，然后又好奇box2d的线程安全怎么做的，发现仅仅通过一个[变量](https://github.com/erincatto/box2d/blob/95f74a46c077825478f989df6a81003ca538c2c2/include/box2d/b2_world.h#L251)控制的，这应该是不可靠的。建议Box2DSharp使用volatile bool _locked来标记，或者用mutex、lock语句。 
使用一个普通类成员变量做多线程同步的标记产生的Bug不一定容易复现（一定会复现），但是不是正确的线程同步方法。

**Comment by Zonciu** [comment]
box2d是非线程安全的，看这里(Is Box2D thread-safe?)[https://github.com/erincatto/box2d/blob/master/docs/FAQ.md#is-box2d-thread-safe]

**Comment by ohsorry** [comment]
是的，我才看过这个页面。我在想在c#里应该总会异步去删除body和关节。难道全部去交给step()的线程去做？

**Comment by ohsorry** [comment]
好吧，应该是我想多了，写多线程程序多了，总希望它能线程安全。
