### ISSUE TITLE
Some problems running on MacOS

### ISSUE THREAD

**Issue by rekcah1986** [Zonciu/Box2DSharp#14]
![image](https://user-images.githubusercontent.com/3055444/134631985-c858859e-7bdb-42c4-824a-200253945ac1.png)

OS Version: Big sur
Unity Version: 2019.4.30f1c2

**Comment by rekcah1986** [comment]
目测还是ImGui的问题，可惜手里没有Windows

**Comment by Zonciu** [comment]
我没有MacOS，你试试Testbed运行是否正常

**Comment by rekcah1986** [comment]
> 我没有MacOS，你试试Testbed运行是否正常

![image](https://user-images.githubusercontent.com/3055444/134636107-f45bbea2-3637-48e3-9ea9-ca14b9f7782d.png)

运行到这句就闪退了，没有报错信息

**Comment by Zonciu** [comment]
你试试看ImGUI.NET仓库里的demo能不能在MacOS下正常运行，如果不能，就是ImGUI.NET的问题；如果能，那就是这里的Shader的问题。

**Comment by rekcah1986** [comment]
https://github.com/mellinoe/ImGui.NET.git
这个试过，可以正常显示

**Comment by Zonciu** [comment]
搞了个虚拟机来测试，目前怀疑是MacOS不支持OpenGL4，我试试改成低版本的OpenGL看看能不能运行
