### ISSUE TITLE
无法访问已释放的对象

### ISSUE THREAD

**Issue by ohsorry** [Zonciu/Box2DSharp#3]
新建了一个winform工程测试了下Box2DSharp。
关闭窗体退出程序就会报这个错：

System.ObjectDisposedException
  HResult=0x80131622
  Message=无法访问已释放的对象。
ObjectDisposed_ObjectName_Name
  Source=mscorlib
  StackTrace:
   在 System.Threading.ThreadLocal`1.GetValueSlow()
   在 System.Threading.ThreadLocal`1.get_Value()
   在 System.Collections.Concurrent.ConcurrentBag`1.GetThreadList(Boolean forceCreate)
   在 System.Collections.Concurrent.ConcurrentBag`1.Add(T item)
   在 Box2DSharp.Common.SimpleObjectPool`1.Return(IEnumerable`1 items) 在 D:\Pro2019\Box2DSharpPlay\Box2DSharp\Common\ObjectPool.cs 中: 第 88 行
   在 Box2DSharp.Collision.DynamicTree.Dispose() 在 D:\Pro2019\Box2DSharpPlay\Box2DSharp\Collision\DynamicTree.cs 中: 第 69 行
   在 Box2DSharp.Collision.DynamicTree.Finalize() 在 D:\Pro2019\Box2DSharpPlay\Box2DSharp\Collision\DynamicTree.cs 中: 第 56 行

======================
代码就new 了一个World，添加了几个body，什么都没做。
退出前手动world.Dispose()也不行。

**Comment by Zonciu** [comment]
请提供一个可复现的例子

**Comment by ohsorry** [comment]
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace Box2DDemo
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            world = new Box2DSharp.Dynamics.World(new System.Numerics.Vector2(0, -9.8F));
        }
        private Box2DSharp.Dynamics.World world = null;
    }
}

**Comment by Zonciu** [comment]
已更新，请pull最新代码测试一下

**Comment by ohsorry** [comment]
不报错了，但是你把析构的链给注释掉了，这样行吗

**Comment by ohsorry** [comment]
等我有时间给你提交代码啊。
可以按参考实现：[IDisposable](https://docs.microsoft.com/zh-cn/dotnet/api/system.idisposable?view=netframework-4.7.2)

**Comment by Zonciu** [comment]
@ohsorry 在Dispose回收即可，析构只应释放非托管资源，这里是之前没考虑全才加进去的，删掉不影响。

**Comment by ohsorry** [comment]
用了对象池不就相当于用了非托管资源吗，析构里调用Dispose()还是必要的。这样忘了手动Dispose()，可复用对象也能被回收。现在貌似只影响BroadPhase、DynamicTree。
